# APENAS BANCO
version: '3.9'

services:
  db:
    image: postgres:12.9-alpine
    container_name: django_vue_backend_dev
    restart: always
    env_file:
      - .env
    volumes:
      - ./config/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
