# Generated by Django 4.0.3 on 2022-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('dateOfJoin', models.DateField()),
                ('photoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
